// <auto-generated />
using System;
using CashierRegister.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CashierRegister.Data.Migrations
{
    [DbContext(typeof(CashierRegisterContext))]
    partial class CashierRegisterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CashierRegister.Data.Entities.Models.CashRegister", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Location");

                    b.HasKey("Id");

                    b.ToTable("CashRegisters");
                });

            modelBuilder.Entity("CashierRegister.Data.Entities.Models.CashRegisterCashier", b =>
                {
                    b.Property<int>("CashRegisterId");

                    b.Property<int>("CashierId");

                    b.Property<DateTime>("EndOfShift");

                    b.Property<DateTime>("StartOfShift");

                    b.HasKey("CashRegisterId", "CashierId");

                    b.HasIndex("CashierId");

                    b.ToTable("CashRegisterCashier");
                });

            modelBuilder.Entity("CashierRegister.Data.Entities.Models.Cashier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password");

                    b.Property<string>("Username")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.ToTable("Cashiers");
                });

            modelBuilder.Entity("CashierRegister.Data.Entities.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CountInStorage");

                    b.Property<string>("Name");

                    b.Property<int>("Price");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("CashierRegister.Data.Entities.Models.Receipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CashRegisterCashierCashRegisterId");

                    b.Property<int?>("CashRegisterCashierCashierId");

                    b.Property<int>("CashRegisterCashierId");

                    b.Property<DateTime>("DateTimeCreated");

                    b.HasKey("Id");

                    b.HasIndex("CashRegisterCashierCashRegisterId", "CashRegisterCashierCashierId");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("CashierRegister.Data.Entities.Models.ReceiptProduct", b =>
                {
                    b.Property<Guid>("ProductId");

                    b.Property<Guid>("ReceiptId");

                    b.HasKey("ProductId", "ReceiptId");

                    b.HasIndex("ReceiptId");

                    b.ToTable("ReceiptProducts");
                });

            modelBuilder.Entity("CashierRegister.Data.Entities.Models.CashRegisterCashier", b =>
                {
                    b.HasOne("CashierRegister.Data.Entities.Models.CashRegister", "CashRegister")
                        .WithMany("CashRegisterCashiers")
                        .HasForeignKey("CashRegisterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CashierRegister.Data.Entities.Models.Cashier", "Cashier")
                        .WithMany("Cashiers")
                        .HasForeignKey("CashierId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CashierRegister.Data.Entities.Models.Receipt", b =>
                {
                    b.HasOne("CashierRegister.Data.Entities.Models.CashRegisterCashier", "CashRegisterCashier")
                        .WithMany()
                        .HasForeignKey("CashRegisterCashierCashRegisterId", "CashRegisterCashierCashierId");
                });

            modelBuilder.Entity("CashierRegister.Data.Entities.Models.ReceiptProduct", b =>
                {
                    b.HasOne("CashierRegister.Data.Entities.Models.Product", "Product")
                        .WithMany("ReceiptProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CashierRegister.Data.Entities.Models.Receipt", "Receipt")
                        .WithMany("ReceiptProducts")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
